# Generated by Django 3.1.1 on 2020-09-21 03:18

from django.db import migrations, models
import django.db.models.deletion
import smart_home.models.device_info
import smart_home.models.device_type


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('info_type', smart_home.models.device_info.StaticModelInfoTypeField(choices=[('switch', 'Switch'), ('thermostat', 'Thermostat'), ('front_door_lock', 'Front Door Lock'), ('sensor', 'Sensor'), ('multi_function', 'Multi-Function')], display_field_name='name', max_length=20, static_model=smart_home.models.device_info.DeviceInfoType, value_field_name='code')),
                ('model_code', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyController',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDevice',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='smart_home.propertycontroller')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_devices', to='smart_home.deviceinfo')),
            ],
            options={
                'unique_together': {('controller', 'url')},
            },
        ),
        migrations.CreateModel(
            name='FrontDoorLockDevice',
            fields=[
                ('base_device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='front_door_locks', serialize=False, to='smart_home.propertydevice')),
                ('pin_digit_count', models.IntegerField()),
                ('master_pin', models.CharField(max_length=8)),
                ('pin_codes', models.JSONField(default=list)),
            ],
            bases=('smart_home.propertydevice',),
        ),
        migrations.CreateModel(
            name='FrontDoorLockInfo',
            fields=[
                ('base_device_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='front_door_lock_info', serialize=False, to='smart_home.deviceinfo')),
                ('type', smart_home.models.device_info.StaticModelInfoTypeField(choices=[('pin_limit_25', 'PIN Limit 25'), ('pin_limit_100', 'PIN Limit 25')], display_field_name='name', max_length=20, static_model=smart_home.models.device_type.FrontDoorLockType, value_field_name='code')),
            ],
            bases=('smart_home.deviceinfo',),
        ),
        migrations.CreateModel(
            name='MultiFunctionInfo',
            fields=[
                ('base_device_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='multi_function_info', serialize=False, to='smart_home.deviceinfo')),
                ('type', smart_home.models.device_info.StaticModelInfoTypeField(choices=[('hum_fld_temp_alm', 'Humidity, Flood, Temp, Alarm'), ('co_smoke_detector', 'Carbon Monoxide & Smoke Detector')], display_field_name='name', max_length=20, static_model=smart_home.models.device_type.MultiFunctionType, value_field_name='code')),
            ],
            bases=('smart_home.deviceinfo',),
        ),
        migrations.CreateModel(
            name='SensorInfo',
            fields=[
                ('base_device_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='sensor_info', serialize=False, to='smart_home.deviceinfo')),
                ('type', smart_home.models.device_info.StaticModelInfoTypeField(choices=[('humidity', 'Humidity'), ('flood', 'Flood'), ('co', 'Carbon Monoxide'), ('smoke', 'Smoke'), ('temp', 'Temperature'), ('window', 'Window')], display_field_name='name', max_length=20, static_model=smart_home.models.device_type.SensorType, value_field_name='code')),
            ],
            bases=('smart_home.deviceinfo',),
        ),
        migrations.CreateModel(
            name='SwitchInfo',
            fields=[
                ('base_device_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='switch_info', serialize=False, to='smart_home.deviceinfo')),
                ('type', smart_home.models.device_info.StaticModelInfoTypeField(choices=[('switch', 'Switch')], display_field_name='name', max_length=20, static_model=smart_home.models.device_type.SwitchType, value_field_name='code')),
            ],
            bases=('smart_home.deviceinfo',),
        ),
        migrations.CreateModel(
            name='ThermostatInfo',
            fields=[
                ('base_device_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='thermostat_info', serialize=False, to='smart_home.deviceinfo')),
                ('type', smart_home.models.device_info.StaticModelInfoTypeField(choices=[('basic', 'Basic'), ('plus_humidity', 'Plus Humidity')], display_field_name='name', max_length=20, static_model=smart_home.models.device_type.ThermostatType, value_field_name='code')),
            ],
            bases=('smart_home.deviceinfo',),
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='smart_home.manufacturer'),
        ),
    ]
